utils (RetryManager): quick fix for error message manuplation
e.cause is actually HTTPError, causing this error:

  File "/home/lesmi/yt-dlp/yt_dlp/utils.py", line 5729, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/lesmi/yt-dlp/yt_dlp/extractor/common.py", line 3853, in _error_or_warning
    RetryManager.report_retry(err, _count or int(fatal), _retries, info=self.to_screen, warn=self.report_warning,
  File "/home/lesmi/yt-dlp/yt_dlp/utils.py", line 5742, in report_retry
    e = remove_end(e.cause or e.orig_msg, '.')
  File "/home/lesmi/yt-dlp/yt_dlp/utils.py", line 2394, in remove_end
    return s[:-len(end)] if s is not None and s.endswith(end) else s
  File "/usr/lib/python3.10/tempfile.py", line 617, in __getattr__
    a = getattr(file, name)
  File "/usr/lib/python3.10/tempfile.py", line 617, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.BytesIO' object has no attribute 'endswith'